<?php
/**
 * AddressDesignApiTest
 * PHP version 8.1
 *
 * @package  ck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * plentymarkets REST-API
 *
 * The plentymarkets REST API expands the functionality of the plentymarkets CMS and allows access to resources, i.e. data records, via unique URI paths
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ck\Test\Api;

use ck\Configuration;
use ck\ApiException;
use ck\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddressDesignApiTest Class Doc Comment
 *
 * @package  ck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressDesignApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for restAddressLayoutCountryCountryIdGet
     *
     * Get layout by country id.
     *
     */
    public function testRestAddressLayoutCountryCountryIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutDefaultGet
     *
     * Get default layout.
     *
     */
    public function testRestAddressLayoutDefaultGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutFieldsGet
     *
     * List all available fields.
     *
     */
    public function testRestAddressLayoutFieldsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutGet
     *
     * List all layouts with their contents.
     *
     */
    public function testRestAddressLayoutGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutPost
     *
     * Create new layout.
     *
     */
    public function testRestAddressLayoutPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutUuidDelete
     *
     * Delete layout.
     *
     */
    public function testRestAddressLayoutUuidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutUuidGet
     *
     * Get layout.
     *
     */
    public function testRestAddressLayoutUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restAddressLayoutUuidPut
     *
     * Update layout.
     *
     */
    public function testRestAddressLayoutUuidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
