<?php
/**
 * ReportApiTest
 * PHP version 8.1
 *
 * @package  ck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * plentymarkets REST-API
 *
 * The plentymarkets REST API expands the functionality of the plentymarkets CMS and allows access to resources, i.e. data records, via unique URI paths
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ck\Test\Api;

use ck\Configuration;
use ck\ApiException;
use ck\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportApiTest Class Doc Comment
 *
 * @package  ck
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for restReportsKeyFiguresConfigGet
     *
     * Returns all key figure configs.
     *
     */
    public function testRestReportsKeyFiguresConfigGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigKeyFigureConfigIdDelete
     *
     * Delete key figure configuration.
     *
     */
    public function testRestReportsKeyFiguresConfigKeyFigureConfigIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigKeyFigureConfigIdGet
     *
     * Get key figure config.
     *
     */
    public function testRestReportsKeyFiguresConfigKeyFigureConfigIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigKeyFigureConfigIdPut
     *
     * Update key figure configuration.
     *
     */
    public function testRestReportsKeyFiguresConfigKeyFigureConfigIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigPost
     *
     * Add a key figure configuration.
     *
     */
    public function testRestReportsKeyFiguresConfigPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigTemplatePost
     *
     * Generate key figure config from template class.
     *
     */
    public function testRestReportsKeyFiguresConfigTemplatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigTemplatesGet
     *
     * Get key figure templates.
     *
     */
    public function testRestReportsKeyFiguresConfigTemplatesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresConfigsDelete
     *
     * Delete multiple key figure configurations.
     *
     */
    public function testRestReportsKeyFiguresConfigsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresDetailsKeyFigureNameGet
     *
     * Return key figure calculation details.
     *
     */
    public function testRestReportsKeyFiguresDetailsKeyFigureNameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresGet
     *
     * Return list of key figure classes.
     *
     */
    public function testRestReportsKeyFiguresGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsKeyFiguresResultsPost
     *
     * Search for key figure calculation results.
     *
     */
    public function testRestReportsKeyFiguresResultsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsOrderTypesGet
     *
     * Get order types in string format.
     *
     */
    public function testRestReportsOrderTypesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsRawDataConfigGet
     *
     * Returns list of all saved configurations.
     *
     */
    public function testRestReportsRawDataConfigGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsRawDataConfigPut
     *
     * Resets all saved raw data configurations with given data.
     *
     */
    public function testRestReportsRawDataConfigPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsRawDataCreatorsConfigsGet
     *
     * Return a list of raw data creators with their configurations.
     *
     */
    public function testRestReportsRawDataCreatorsConfigsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsRawDataCreatorsGet
     *
     * Get list of all raw data creators.
     *
     */
    public function testRestReportsRawDataCreatorsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsRawDataFileGet
     *
     * Get a raw data file from the storage, the storage path of the file must be specified..
     *
     */
    public function testRestReportsRawDataFileGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restReportsRawDataGet
     *
     * Get list of raw data files. Valid filter combinations: (dataName), (dataName & processStatus), (createdAtTimestamp).
     *
     */
    public function testRestReportsRawDataGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
